apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chacha
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: chacha
spec:
  project: hhara
  source:
    repoURL: https://github.com/Himalayan-wildcat/argocd-test
    targetRevision: HEAD 
    path: manifests/nginx
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: hhara
  syncPolicy:
    automated: 
      prune: true
      enabled: false
